on: [push, pull_request]
name: Build and Test
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: lint
        run: make lint